import type { Language } from "./i18n.js";
import type { DictationError } from "../core/dictation.js";

interface Copy {
  dictate: string; stop: string; cancel: string; retry: string; requesting: string; recording: string; processing: string; done: string; privacy: string; level: string; leave: string;
  errors: Record<DictationError, string>;
}
export const dictationText: Record<Language, Copy> = {
  ru: {
    dictate: "Надиктовать", stop: "Готово — расшифровать", cancel: "Отменить", retry: "Повторить расшифровку", requesting: "Открываем микрофон…", recording: "Идёт запись", processing: "Расшифровываем на сервере OpenAI…", done: "Текст добавлен. Проверьте его перед отправкой.", privacy: "Аудио отправляется в OpenAI. Приложение не сохраняет запись. Текст сначала появится в черновике.", level: "Уровень микрофона", leave: "Запись или расшифровка ещё идёт. Перейти и отменить её? Уже введённый текст останется.",
    errors: { auth: "Откройте Codex и войдите через ChatGPT, затем повторите расшифровку. API-ключ для диктовки не подходит.", permission: "Разрешите Family Bridge доступ к микрофону в настройках конфиденциальности системы, затем попробуйте снова.", microphone: "Микрофон недоступен. Проверьте, подключён ли он и не занят ли другим приложением.", busy: "Другая запись ещё обрабатывается. Подождите и повторите.", invalid_audio: "Не удалось прочитать запись. Попробуйте записать ещё раз.", empty: "Речь не распознана. Проверьте микрофон и запишите ещё раз.", network: "Нет связи с OpenAI. Текст не изменён; можно повторить расшифровку этой записи.", timeout: "Расшифровка заняла слишком долго. Можно повторить без новой записи.", unavailable: "Сервис диктовки временно недоступен. Повторите позже или введите текст.", limit: "Сервис просит подождать. Повторите позже или введите текст.", cancelled: "Диктовка отменена. Ваш текст не изменён." },
  },
  en: {
    dictate: "Dictate", stop: "Done — transcribe", cancel: "Cancel", retry: "Retry transcription", requesting: "Opening microphone…", recording: "Recording", processing: "Transcribing on OpenAI’s server…", done: "Text added. Review it before sending.", privacy: "Audio is sent to OpenAI. The app does not save the recording. Text goes into your draft first.", level: "Microphone level", leave: "Recording or transcription is in progress. Leave and cancel it? Your existing text will remain.",
    errors: { auth: "Open Codex and sign in with ChatGPT, then retry. Dictation does not use an API key.", permission: "Allow Family Bridge microphone access in your system privacy settings, then try again.", microphone: "Microphone unavailable. Check that it is connected and not in use by another app.", busy: "Another recording is still processing. Wait and retry.", invalid_audio: "Could not read the recording. Please record again.", empty: "No speech recognized. Check your microphone and record again.", network: "Cannot reach OpenAI. Your text is unchanged; retry this recording.", timeout: "Transcription took too long. Retry without recording again.", unavailable: "Dictation is temporarily unavailable. Retry later or type your answer.", limit: "The service asks you to wait. Retry later or type your answer.", cancelled: "Dictation cancelled. Your text is unchanged." },
  },
  cs: {
    dictate: "Nadiktovat", stop: "Hotovo — přepsat", cancel: "Zrušit", retry: "Zkusit přepis znovu", requesting: "Otevíráme mikrofon…", recording: "Nahráváme", processing: "Přepisujeme na serveru OpenAI…", done: "Text byl doplněn. Před odesláním jej zkontrolujte.", privacy: "Zvuk se odešle do OpenAI. Aplikace nahrávku neukládá. Text se nejprve vloží do konceptu.", level: "Úroveň mikrofonu", leave: "Nahrávání nebo přepis stále probíhá. Přejít a zrušit jej? Již napsaný text zůstane.",
    errors: { auth: "Otevřete Codex, přihlaste se přes ChatGPT a opakujte přepis. Diktování nepoužívá API klíč.", permission: "Povolte Family Bridge přístup k mikrofonu v nastavení soukromí systému a zkuste to znovu.", microphone: "Mikrofon není dostupný. Zkontrolujte připojení a ostatní aplikace.", busy: "Jiná nahrávka se ještě zpracovává. Počkejte a zkuste to znovu.", invalid_audio: "Nahrávku nelze přečíst. Nahrajte ji znovu.", empty: "Řeč nebyla rozpoznána. Zkontrolujte mikrofon a nahrajte ji znovu.", network: "Nelze se spojit s OpenAI. Text se nezměnil; přepis lze zopakovat.", timeout: "Přepis trval příliš dlouho. Lze jej zopakovat bez nové nahrávky.", unavailable: "Diktování je dočasně nedostupné. Zkuste to později nebo napište odpověď.", limit: "Služba žádá o vyčkání. Zkuste to později nebo napište odpověď.", cancelled: "Diktování zrušeno. Váš text se nezměnil." },
  },
  fr: {
    dictate: "Dicter", stop: "Terminer et transcrire", cancel: "Annuler", retry: "Réessayer la transcription", requesting: "Ouverture du microphone…", recording: "Enregistrement", processing: "Transcription sur le serveur OpenAI…", done: "Texte ajouté. Vérifiez-le avant de l’envoyer.", privacy: "L’audio est envoyé à OpenAI. L’application ne conserve pas l’enregistrement. Le texte apparaît d’abord dans votre brouillon.", level: "Niveau du microphone", leave: "L’enregistrement ou la transcription est en cours. Quitter et l’annuler ? Le texte déjà saisi sera conservé.",
    errors: { auth: "Ouvrez Codex, connectez-vous avec ChatGPT, puis réessayez. La dictée n’utilise pas de clé API.", permission: "Autorisez l’accès au microphone pour Family Bridge dans les réglages de confidentialité du système.", microphone: "Microphone indisponible. Vérifiez sa connexion et les autres applications.", busy: "Un autre enregistrement est encore en cours de traitement. Patientez et réessayez.", invalid_audio: "Enregistrement illisible. Veuillez recommencer.", empty: "Aucune parole reconnue. Vérifiez le microphone et recommencez.", network: "OpenAI est injoignable. Le texte est intact ; réessayez cet enregistrement.", timeout: "La transcription a pris trop de temps. Réessayez sans réenregistrer.", unavailable: "La dictée est temporairement indisponible. Réessayez plus tard ou saisissez votre réponse.", limit: "Le service demande de patienter. Réessayez plus tard ou saisissez votre réponse.", cancelled: "Dictée annulée. Votre texte est intact." },
  },
};
