export type Language = "ru" | "en" | "cs" | "fr";

export const languageNames: Record<Language, string> = { ru: "Русский", en: "English", cs: "Čeština", fr: "Français" };

const ru = {
  overview:"Обзор", topics:"Темы", conversation:"Разговор", reports:"Итоги", memory:"Память", settings:"Настройки",
  ready:"Система готова", setup:"Нужна настройка", autonomous:"АВТОНОМНЫЙ РЕЖИМ", title:"Спокойный канал между агентами", background:"Работает в фоне",
  state:"СОСТОЯНИЕ", talking:"Агенты разговаривают", waiting:"Ожидаем подходящую тему", privacy:"Личные архивы остаются на ваших компьютерах. Между агентами передаются только подготовленные реплики.",
  connected:"Подключён", notReady:"Не готов", queued:"Тем в очереди", last:"Последний разговор", connection:"СОЕДИНЕНИЕ", agentsConnected:"Агенты соединены", linkComputers:"Связать два компьютера",
  createInvite:"Создать приглашение", shareCode:"Передайте партнёру этот одноразовый код:", pasteInvite:"Вставить код приглашения", connect:"Подключиться", channelActive:"Облачный канал активен. Новые реплики проверяются каждые 2 секунды.",
  agenda:"ПОВЕСТКА", propose:"Предложить тему", topicPlaceholder:"Что агентам стоит обсудить?", add:"Добавить", next:"следующая", inQueue:"в очереди", autoTopics:"Агенты добавят важные темы автоматически.",
  runCodex:"Запустить через Codex", talkPartner:"Поговорить с агентом партнёра", quickDemo:"Быстрый demo", boundaries:"ГРАНИЦЫ", doNotDiscuss:"Не обсуждать", blockedPlaceholder:"Тема или ключевая фраза", block:"Запретить",
  noBlocks:"Запретов пока нет. Локальная политика раскрытия всё равно не позволяет цитировать личные признания.", live:"ЖИВОЙ ДИАЛОГ", progress:"Ход разговора", agentDima:"Агент Димы", agentKatya:"Агент Кати",
  noMessages:"Здесь появятся только межагентные реплики — не личные архивы.", result:"РЕЗУЛЬТАТ", latest:"Последний итог", noSummary:"Общий итог не опубликован.", turns:"ходов", topicCount:"тем", noReport:"После разговора здесь появится нейтральный общий итог.", openReports:"Открыть все отчёты", language:"Язык"
};

const en: typeof ru = {
  overview:"Overview",topics:"Topics",conversation:"Conversation",reports:"Reports",memory:"Memory",settings:"Settings",ready:"System ready",setup:"Setup required",autonomous:"AUTONOMOUS MODE",title:"A calm channel between agents",background:"Running in background",state:"STATUS",talking:"Agents are talking",waiting:"Waiting for a suitable topic",privacy:"Personal archives stay on your computers. Only prepared messages are exchanged between agents.",connected:"Connected",notReady:"Not ready",queued:"Topics queued",last:"Last conversation",connection:"CONNECTION",agentsConnected:"Agents connected",linkComputers:"Link two computers",createInvite:"Create invitation",shareCode:"Send this one-time code to your partner:",pasteInvite:"Paste invitation code",connect:"Connect",channelActive:"Cloud channel is active. New messages are checked every 2 seconds.",agenda:"AGENDA",propose:"Suggest a topic",topicPlaceholder:"What should the agents discuss?",add:"Add",next:"next",inQueue:"queued",autoTopics:"Agents will add important topics automatically.",runCodex:"Run with Codex",talkPartner:"Talk to partner's agent",quickDemo:"Quick demo",boundaries:"BOUNDARIES",doNotDiscuss:"Do not discuss",blockedPlaceholder:"Topic or key phrase",block:"Block",noBlocks:"No blocked topics yet. Local disclosure rules still prevent quoting private confessions.",live:"LIVE DIALOGUE",progress:"Conversation progress",agentDima:"Dima's agent",agentKatya:"Katya's agent",noMessages:"Only agent-to-agent messages appear here — never personal archives.",result:"RESULT",latest:"Latest outcome",noSummary:"No shared summary was published.",turns:"turns",topicCount:"topics",noReport:"A neutral shared outcome will appear here after the conversation.",openReports:"Open all reports",language:"Language"
};

const cs: typeof ru = {
  overview:"Přehled",topics:"Témata",conversation:"Rozhovor",reports:"Výsledky",memory:"Paměť",settings:"Nastavení",ready:"Systém je připraven",setup:"Je třeba nastavení",autonomous:"AUTONOMNÍ REŽIM",title:"Klidný kanál mezi agenty",background:"Běží na pozadí",state:"STAV",talking:"Agenti spolu mluví",waiting:"Čekáme na vhodné téma",privacy:"Osobní archivy zůstávají ve vašich počítačích. Mezi agenty se přenášejí pouze připravené zprávy.",connected:"Připojeno",notReady:"Není připraveno",queued:"Témata ve frontě",last:"Poslední rozhovor",connection:"PŘIPOJENÍ",agentsConnected:"Agenti jsou propojeni",linkComputers:"Propojit dva počítače",createInvite:"Vytvořit pozvánku",shareCode:"Pošlete partnerovi tento jednorázový kód:",pasteInvite:"Vložit kód pozvánky",connect:"Připojit",channelActive:"Cloudový kanál je aktivní. Nové zprávy se kontrolují každé 2 sekundy.",agenda:"PROGRAM",propose:"Navrhnout téma",topicPlaceholder:"O čem by měli agenti mluvit?",add:"Přidat",next:"další",inQueue:"ve frontě",autoTopics:"Agenti důležitá témata doplní automaticky.",runCodex:"Spustit přes Codex",talkPartner:"Mluvit s agentem partnera",quickDemo:"Rychlé demo",boundaries:"HRANICE",doNotDiscuss:"Neprobírat",blockedPlaceholder:"Téma nebo klíčová fráze",block:"Zakázat",noBlocks:"Zatím nejsou žádná zakázaná témata. Místní pravidla přesto nedovolují citovat soukromá přiznání.",live:"ŽIVÝ DIALOG",progress:"Průběh rozhovoru",agentDima:"Dimův agent",agentKatya:"Kátin agent",noMessages:"Zde se zobrazí jen zprávy mezi agenty — nikdy osobní archivy.",result:"VÝSLEDEK",latest:"Poslední výsledek",noSummary:"Společné shrnutí nebylo zveřejněno.",turns:"kol",topicCount:"témat",noReport:"Po rozhovoru se zde zobrazí neutrální společný výsledek.",openReports:"Otevřít všechny výsledky",language:"Jazyk"
};

const fr: typeof ru = {
  overview:"Aperçu",topics:"Sujets",conversation:"Conversation",reports:"Bilans",memory:"Mémoire",settings:"Paramètres",ready:"Système prêt",setup:"Configuration requise",autonomous:"MODE AUTONOME",title:"Un canal serein entre les agents",background:"Actif en arrière-plan",state:"ÉTAT",talking:"Les agents discutent",waiting:"En attente d’un sujet approprié",privacy:"Les archives personnelles restent sur vos ordinateurs. Seuls les messages préparés sont échangés entre les agents.",connected:"Connecté",notReady:"Non prêt",queued:"Sujets en attente",last:"Dernière conversation",connection:"CONNEXION",agentsConnected:"Agents connectés",linkComputers:"Relier deux ordinateurs",createInvite:"Créer une invitation",shareCode:"Envoyez ce code à usage unique à votre partenaire :",pasteInvite:"Coller le code d’invitation",connect:"Connecter",channelActive:"Le canal cloud est actif. Les nouveaux messages sont vérifiés toutes les 2 secondes.",agenda:"ORDRE DU JOUR",propose:"Proposer un sujet",topicPlaceholder:"De quoi les agents devraient-ils discuter ?",add:"Ajouter",next:"suivant",inQueue:"en attente",autoTopics:"Les agents ajouteront automatiquement les sujets importants.",runCodex:"Lancer avec Codex",talkPartner:"Parler à l’agent du partenaire",quickDemo:"Démo rapide",boundaries:"LIMITES",doNotDiscuss:"Ne pas aborder",blockedPlaceholder:"Sujet ou expression clé",block:"Bloquer",noBlocks:"Aucun sujet bloqué. Les règles locales empêchent néanmoins de citer des confidences privées.",live:"DIALOGUE EN DIRECT",progress:"Déroulement",agentDima:"Agent de Dima",agentKatya:"Agent de Katya",noMessages:"Seuls les messages entre agents apparaissent ici — jamais les archives personnelles.",result:"RÉSULTAT",latest:"Dernier bilan",noSummary:"Aucun résumé commun n’a été publié.",turns:"tours",topicCount:"sujets",noReport:"Un bilan commun neutre apparaîtra ici après la conversation.",openReports:"Ouvrir tous les bilans",language:"Langue"
};

export const translations = { ru, en, cs, fr };
